apiVersion: v2
appVersion: v1.8.1-n4kbuild.1
description: Kubernetes Native Policy Management
home: https://kyverno.io/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- policy engine
- validating webhook
- admissions controller
kubeVersion: '>=1.16.0-0'
maintainers:
- name: Nirmata
  url: https://nirmata.com/
name: kyverno
sources:
- https://github.com/kyverno/kyverno
version: v1.5.0
