# permissions for end users to edit enterprisekyvernoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: enterprisekyverno-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: enterprise-kyverno
    app.kubernetes.io/part-of: enterprise-kyverno
    app.kubernetes.io/managed-by: kustomize
  name: enterprisekyverno-editor-role
rules:
- apiGroups:
  - security.nirmata.io
  resources:
  - enterprisekyvernoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.nirmata.io
  resources:
  - enterprisekyvernoes/status
  verbs:
  - get
