# permissions for end users to edit openshiftkyvernooperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openshiftkyvernooperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-kyverno-operator
    app.kubernetes.io/part-of: openshift-kyverno-operator
    app.kubernetes.io/managed-by: kustomize
  name: openshiftkyvernooperator-editor-role
rules:
- apiGroups:
  - operator.nirmata.io
  resources:
  - openshiftkyvernooperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.nirmata.io
  resources:
  - openshiftkyvernooperators/status
  verbs:
  - get
