{{ range $name, $secret := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "kyverno.labels" $ | nindent 4 }}
    app: kyverno
  name: {{ $name }}
  namespace: {{ template "kyverno.namespace" $ }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "kyverno.imagePullSecret" $secret }}
{{ end }}
{{ if and .Values.imagePullSecret.name .Values.imagePullSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ include "kyvernoMonitorNamespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretDockerConfig" . }}
{{- end }}
